### ISSUE TITLE
Black bar in iOS11 devices

### ISSUE THREAD

**Issue by nicolettemanas** [dogo/AKSideMenu#35]
Hello,

Noticed some black bar on top of the Navigation Bar when menu is displayed in any device running on iOS11.

![simulator screen shot - ipad air - 2017-11-29 at 13 01 45](https://user-images.githubusercontent.com/3390967/33358795-d0441760-d505-11e7-806c-a91bc24e44ad.png)
![simulator screen shot - iphone 6s - 2017-11-29 at 12 58 43](https://user-images.githubusercontent.com/3390967/33358796-d0830e70-d505-11e7-91fa-e2f73a1f14a6.png)
![simulator screen shot - iphone 6s - 2017-11-29 at 13 02 43](https://user-images.githubusercontent.com/3390967/33358797-d0b97852-d505-11e7-9afb-411dc8b7ba27.png)

 - AKSideMenu version: `1.4.0`
 - Device OS version: `11.1`
 - Device Name: `Simulator iPhone X, iPad Air, iPhone 6s`

**Comment by dogo** [comment]
Black/white space on top of scaled ContentViewController #29

**Comment by nicolettemanas** [comment]
Checking off Translucent from the Navigation Bar doesn't seem to work. Same problem with ASKSideMenu Simple example.

**Comment by dogo** [comment]
@nicolettemanas please test the develop branch, commit 4c62fcf95ea8ac6321d3628f3bb5b7311d15f75b should fix it

**Comment by nicolettemanas** [comment]
hi @dogo,

The fix works great on Portrait. I am still seeing the same issue when used with iPhones iOS11 on _landscape_ though. 

I tried changing the content of `updateContentViewAdditionalSafeAreaInsets` to the ff:

```
 func updateContentViewAdditionalSafeAreaInsets() {
        if #available(iOS 11.0, *) {
            if var insets = self.contentViewController?.additionalSafeAreaInsets {
                insets.top = self.contentViewContainer.frame.minY
                if insets.top < 0.0 {
                    insets.top = 0.0
                }
                self.contentViewController?.additionalSafeAreaInsets = insets
            }
        }
    }
```

and that seems to be working. I just removed the part of getting `self.view.safeAreaLayoutGuide.layoutFrame.minY` and setting it as the top inset. 

Let me know if this is okay to send as a pull request as I am not that familiar with `safeAreaLayoutGuide` yet.

Thanks!

**Comment by dogo** [comment]
@nicolettemanas 
hum thats weird, seems fine for me running on Portrait or Landscape, could you please make a video showing the issue?

**Comment by nicolettemanas** [comment]
Hi @dogo

**Comment by nicolettemanas** [comment]
Hi @dogo 

It does seem weird. The fix is not working on a real iOS device but is working on Portrait for Simulator. Please see ff GIFs:

`Simulator, iPhone6plus iOS11.1`
![simulator-iphone6plus-ios11 1](https://user-images.githubusercontent.com/3390967/34285235-0ea9dcaa-e713-11e7-9b0a-81d9e739427d.gif)

`Device iPhone6plus iOS11.0`
![device-iphone6plus-ios11 0](https://user-images.githubusercontent.com/3390967/34285238-10b1f672-e713-11e7-8025-020351d54e0a.gif)

Please also note that I also tried to test it without the recording bar at the top and got the same result.

These are from branch `develop` on commit `453249c`

Let me know if you need further details 😃

**Comment by dogo** [comment]
Bug fixed
